name: Kinonation
description: Cloud based global VOD distribution for everyone
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
social: false
offline: true
url: http://kinonation.com
permalink: none
gems:
  - jekyll-sitemap
sass:
  style: compressed
