name: Kinonation
description: Cloud based global video streaming service distribution for everyone
social: false
offline: true
url: http://kinonation.com
permalink: none
gems:
  - jekyll-sitemap
sass:
  # style: compressed
  sourcemap: inline
  # debug_info: true
  line_numbers: true
  line_comments: true
