title: Filmhub
description: Film distribution marketplace for indie filmmakers and video streaming services
social: false
offline: true
url: http://filmhub.com
permalink: none
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag
sass:
  # style: compressed
  sourcemap: inline
  # debug_info: true
  line_numbers: true
  line_comments: true
