name: Filmhub
description: Filmhub is an online film distribution platform matching millions of video programs with thousands of streaming services.
social: false
offline: true
url: http://filmhub.com
permalink: none
plugins:
  - jekyll-sitemap
sass:
  # style: compressed
  sourcemap: inline
  # debug_info: true
  line_numbers: true
  line_comments: true
